### PR TITLE
Closes #1448: fix process ID fetch for Galaxy S5

### LINKED ISSUE #1448: On Android, incorrect pid is returned on Galaxy S5 (an old device), providing invalid results for processStartTime
### Steps to reproduce
I'm a Mozilla developer running browsertime through our `mach perftest` harness. I was unable to figure out how to run browsertime standalone so I couldn't provide a smaller reproducible test case.
- Set up mozilla-central (probably clone and run `./mach create-mach-environment`)
- Plug in Galaxy S5 (or probably similarly old devices – shell commands have varied behavior on old devices)
- Install Firefox Nightly
- Run `./mach perftest` (e.g.
```
#!/usr/bin/env zsh

#./mach perftest \
python3 python/mozperftest/mozperftest/runner.py \
    --flavor mobile-browser \
    --android \
    --android-app-name org.mozilla.fenix \
    --perfherder-metrics processLaunchToNavStart \
    --android-activity org.mozilla.fenix.IntentReceiverActivity \
    --android-clear-logcat \
    --android-capture-logcat logcat \
    --hooks testing/performance/hooks_android_view.py \
    --perfherder \
    --perfherder-app fenix \
    --browsertime-iterations 5 \
    --output sb/artifacts \
    --browsertime-geckodriver ~/Downloads/geckodriver\ 3 \
    --browsertime-binary ~/dev/ref/browsertime/bin/browsertime.js \
    testing/performance/perftest_android_view.js
```

### Expected results
Valid runtime results.

### Actual results
Invalid runtime results: the replicates (i.e. time for each run) keep increasing:
> "replicates": [342603, 367380, 392318, 417116, 442098, 466967, 492591, 517842, 542610, 567952, 592352, 617368, 642265, 666794, 691967, 717060, 742357, 767901, 792718, 817542, 842695, 868057, 893527, 917921, 943165]

After investigating, I found:
- the `processStartTime` is incorrect https://searchfox.org/mozilla-central/source/testing/performance/perftest_android_view.js#16
- because the pid used to calculate it is incorrect (it's always `1`): https://github.com/sitespeedio/browsertime/blob/5a20f579f393451136f41dae8f74dc07a192d93a/lib/android/index.js#L290
- the pid is incorrect because the shell command `pidof` on the Galaxy S5 https://github.com/sitespeedio/browsertime/blob/5a20f579f393451136f41dae8f74dc07a192d93a/lib/android/index.js#L245 returns all active process IDs instead of just one, e.g. "1 2 3 6 7 8 21 22 28 29..."

I'm tracking this issue on our issue tracker in https://bugzilla.mozilla.org/show_bug.cgi?id=1667223 and will soon open a PR to address it.

### Additional info
- URL: any
- log output: I only know how to get the `mach perftest` output and not the browsertime output. Let me know if you need it though
- version: reproduces as early as 9.4.1 and as late as main a2f1e73a 
- macOS 10.15.7, no docker
- browser: Firefox for Android Nightly (around 12/1/2020)

### PR DESCRIPTION
**Pull request by mcomella**
This fixes the process ID issue on the Galaxy S5 described in #1448. I was unable to run browsertime standalone but it fixes the issue within Mozilla's `./mach perftest` harness on this device.

Unfortunately, the perftest harness is currently broken on my Pixel 2 (https://bugzilla.mozilla.org/show_bug.cgi?id=1667224) so I'm unable to test on other devices. In particular, I'm concerned that the one non-trivial line I added, `!ps.trim().includes(' ') &&` will go untested (at least until I can fix our test harness for P2 or figure out how to run browsertime standalone). Otherwise, I didn't modify the codepath much I expect it to use (using `pidof`) so I think it should work correctly. I similarly confirmed the Moto G5 returns the expected output from pidof and should work correctly.

I don't know how to run the tests so I didn't run them. It doesn't look like a unit test harness is set up for these classes so I didn't write new tests.

Sorry for the lackluster testing and reproducible test case story but hopefully I've been descriptive enough to help out. :)

### CODE REVIEW

**Comment by soulgalore** [comment]
HI @mcomella thanks for the fix, I'm adding @gmierz as reviewer maybe you point out if you want anyone else to look at it. At the moment I only have G4, G5 and a Alcatel X1 to run my tests and I haven't actually tested the functionality you are fixing.

It seems like your code isn't linting, if you don't have your editor setup to follow Browsertime setup, you can just run `npm run lint:fix` to fix the linting and push the change.

If you want to run Browsertime standalone on your machine you need to have NodeJS installed (10 or later) and then Firefox (of course :)). Then run `npm install browsertime -g` and run  `browsertime --help` for all the options.

**Comment by mcomella** [comment]
> I'm adding @gmierz as reviewer

Sounds good. I'm in contact with them and will work through it with them.

> just run npm run lint:fix to fix the linting and push the change.

Done.

> If you want to run Browsertime standalone on your machine you need to have NodeJS installed (10 or later) and then Firefox (of course :)). Then run npm install browsertime -g and run browsertime --help for all the options.

Will that let me test with my local changes? I didn't see any options to run browsertime with local changes in that binary. Earlier, I tried using `node bin/browsertime.js` with the arguments as suggested in the examples but it failed to run (I don't remember the error but I can reconstruct it if you'd like).

**Comment by mcomella** [comment]
I made a try push to test this change in mozilla-central: https://treeherder.mozilla.org/jobs?repo=try&revision=8d0565464c5f232484471678830e3017415a13e4 I forgot to include the commit with the lint fix but that was entirely automated so it's probably fine.

**Comment by soulgalore** [comment]
Ah sorry, I meant of course running the local test with`./bin/browsertime.js ` in your local branch with your fixes, that new code will be tested.

Thanks for your fix, wanna check if someone from the Mozilla team has time to have a look. 👍

**Review by gmierz — APPROVED** [review]
Everything looks good for me! Thanks for testing it on try @mcomella.

**Comment by soulgalore** [comment]
Thank you @mcomella !

**Pull request merged**
