### PR TITLE
Add option for specifying logging format in visualmetrics.py.

### PR DESCRIPTION
**Pull request by gmierz**
This patch adds an option to specify the log formatting in the visualmetrics.py script.

### CODE REVIEW

**Comment by soulgalore** [comment]
Thank you @gmierz ! One thing: Do you use Python 2 or 3 in your setup? I'm wondering about https://github.com/sitespeedio/browsertime/issues/1142#issuecomment-697318411 that for me no log for Visual Metrics is created when I run Python 3.

**Comment by gmierz** [comment]
Hmm, we run it with Python 3 actually and I'm able to get logs from it but we don't use log files though so I haven't checked that.

**Comment by gmierz** [comment]
I checked locally with the --logfile option just now and I'm seeing logging going into the file and it being created so it sounds like something within browsertime that is causing issues.

**Comment by soulgalore** [comment]
Ok cool thanks.

**Pull request merged**
