### PR TITLE
Expose cli module and added getOptions() method to get cli options

### PR DESCRIPTION
**Pull request by moos**
Allows parent components to easily reuse browsertime yargs cli options:

``` js
var browsertimeCli = require('browsertime').cli;
let browsertimeOptions = browsertimeCli.getOptions({
  group: 'Browser',
  prefix: 'browsertime.',
  forceGroup: true
});

yargs().options(browsertimeOptions ).option(...)
```

Parent component's help:

``` shell
Browser
  --browsertime.timeouts.browserStart                     Timeout when waiting for browser to start, in milliseconds
                                                                                                                 [number] [default: 60000]

  --browsertime.timeouts.pageLoad                         Timeout when waiting for url to load, in milliseconds [number] [default: 300000]
...
```

### CODE REVIEW

**Comment by tobli** [comment]
Thanks for doing this! I've been thinking about something along these lines. I'd propose to do the filtering of "cli-related" (only relevant when browsertime is run standalone) in browsertime, and not in sitespeed. E.g. separating into getOptions and getCliOptions, and only exporting the first of the two. I think that's a cleaner separation of concerns.

**Comment by tobli** [comment]
I'd prefer aliases to not be exported as well. They are also more cli-centric, and might not be a good fit for sitespeed. The approach in https://github.com/sitespeedio/sitespeed.io/pull/1225 to list aliases explicitly is better I think.

**Comment by moos** [comment]
So cli options would be things like 'silent', 'har', 'output', etc?   I agree -- that would ease the container from having to do the filtering.  I can start with the remove list.  What else would you add there?
```js
removeOptions = ['output', 'silent', 'har', 'skipHar', 'resultDir', 'config'];
```
As for aliases, there is the benefit of continuing/consistency in keeping the same aliases (e.g. `-n-`, `-b`).  But it could lead to conflicts.  Perhaps a `keepAliases` option?

**Comment by tobli** [comment]
Great list, I'd add prettyPrint as well. Let's keep aliases as they are now in the PR, and we can revisit it later if there's a potential conflict. Thanks!

**Comment by soulgalore** [comment]
@tobli is there anything more that needs to be done here or can we merge it? Would be great to get this in and then see if we can reuse the pattern for new (standalone) plugins.

**Comment by soulgalore** [comment]
hey @moos 
do you have time to fix the conflict? Working on fixing as much as possible before 4.0 next week :)

Best
Peter

**Comment by soulgalore** [comment]
I don't think this has a high prio, let us close this and if we ever feel we need re-open.

**Pull request closed without merging**
