### PR TITLE
Add iteration set delay support

### PR DESCRIPTION
**Pull request by SamuliR**
used for --browsertime.iterationSetDelay

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @SamuliR is this the same as https://github.com/sitespeedio/browsertime/blob/master/lib/core/engine/index.js#L132-L134 ? I didn't fully get that. 

Best
Peter

**Comment by SamuliR** [comment]
iterationSetDelay is the delay in-between a set of iterations so it waits a little bit before the next bombardment

iteration - delay - iteration - delay - iteration 
**iterationSetDelay** 

iteration - delay - iteration - delay - iteration
**iterationSetDelay** 

and so on

**Comment by matti** [comment]
@soulgalore so that you can run 10 iterations with normal delay, for example, 10s and then sleep 500s.

effectively: test 10 iterations, sleep 500s, test 10 iterations... currently this is impossible - we have successfully run monitoring tests like this so that we get more samples per time and then pause.

**Comment by soulgalore** [comment]
Yeah but do you really need that in browsertime or how do you run it?

```
browsertime ...
sleep 10 
browsertime ...
```

Or is the use case you test multiple URLs from sitespeed.io? Then I think we could ad that directly in sitespeed.io so we have an extra delay/wait before moving on to next URL.

**Comment by matti** [comment]
when running with sitespeed with docker (the pre-built sitespeed image, not browsertime) it would be super handy!

**Comment by soulgalore** [comment]
Yep let me add it before the next release.

**Pull request closed without merging**
