### PR TITLE
Connectivity engine throttled outside of Browsertime

### PR DESCRIPTION
**Pull request by soulgalore**

### CODE REVIEW

**Comment by worenga** [comment]
1. ) I am not sure why this is necessary. When profile is native neither tc nor tsproxy are started?
2. ) Also throttled might be a confusing name for essentially a no-op.

**Comment by soulgalore** [comment]
1) It seems like the best way to throttle a connection for Docker is to do it on a bridge (https://github.com/sitespeedio/browsertime/issues/271#issuecomment-281171534) so we need to that outside the container. There could be other ways of fixing this in the future but one that at least would work now is the bridge solution.

2) Yes a better name sounds good, let see if @tobli and @beenanner has any suggestions.

**Comment by tobli** [comment]
We're not currently picking up connectivity profile/name from Browsertime when creating Graphite metric paths, are we? That'd be a great use case for this. Also storing throttling settings in the Browsertime result json, when run stand alone (to remember the settings used when doing the measurement). One option to name a specific set of conditions (either throttled, or run e.g. via a tethered phone) would be to call the engine "named", to indicate that it's a given set of network conditions that we want to associate with a name.

**Comment by soulgalore** [comment]
> We're not currently picking up connectivity profile/name from Browsertime when creating Graphite metric paths, are we?

No but since it is the same API it's clean to have it implemented in BT and then just add the CLI in sitespeed.io. 

Agree we should have it in the JSON output in BT. 

Naming is hard :)

**Pull request merged**
