### PR TITLE
Get CPU metrics using Glean

### PR DESCRIPTION
**Pull request by afinder-mozilla**
Using Glean to extract CPU/Power metrics

### CODE REVIEW

**Comment by afinder-mozilla** [comment]
@soulgalore Hi Peter! This PR is for porting the CPU/Power metrics to browsertime. Applying these changes to version 16.7.0 leads to some conflicts. Would it be ok to apply these changes to latest version of main ?

**Comment by soulgalore** [comment]
Hi @afinder-mozilla yes please, push it to main that is perfect. Always push to main and move forward :) Can you fix that conflict? In main I've changes so we follow the same pattern for checking if we are testing on Android (`isAndroidConfigured(this.options)` to be able to move Android specific configuration to -`-android.yourconfig`.

**Comment by afinder-mozilla** [comment]
@soulgalore Thank you for the reply Peter! I'll make the changes and update the PR then.

**Comment by afinder-mozilla** [comment]
I opened a new [PR](https://github.com/sitespeedio/browsertime/pull/1875) for the changes. Please discard this PR.

**Pull request closed without merging**
