### PR TITLE
Expose trace start/stop

### PR DESCRIPTION
**Pull request by 92kns**
Hello! I'd like to expose the start/stop for the chrome Trace similar to how it was done with the gecko profiler in https://github.com/sitespeedio/browsertime/pull/1934 and https://github.com/sitespeedio/browsertime/pull/1940

Does the implementation here make sense?

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @92kns yes that would be cool. I'll have a look tomorrow and will get back then.

**Comment by soulgalore** [comment]
Oh sorry I forgot about this, let me have a look tonight. There were a couple small fixes but I can fix those. I haven't tried the functionality yet though :)

**Comment by 92kns** [comment]
no worries, sounds good! thanks :)

**Comment by soulgalore** [comment]
Thank you @92kns ! I will do follow up PR with small refactoring, just so we don't have the same functionality twice. Thank you again!

**Comment by 92kns** [comment]
Awesome thanks!

**Pull request merged**
