### PR TITLE
[NodeJs] [Windows 10] Add run

### PR DESCRIPTION
**Pull request by GeekZebre**
Code for run browsertime with NodeJs on Windows 10.

### CODE REVIEW

**Comment by GeekZebre** [comment]
Which IDE do you use ?

**Comment by GeekZebre** [comment]
Hi @soulgalore 
I understand.

I developp on Windows 10 and I think create my own plugin.
But I don't think running performance tests on windows in a production mode.
It's just for testing.

So, I will continue to have my own version of browsertime.

Thanks.

**Comment by beenanner** [comment]
I use visual studio code as well. :-)

**Comment by soulgalore** [comment]
Closing this since we will not merge until we have someone who can join the team and be our Windows specialist. Thanks for the PR though it's a good start!

**Pull request closed without merging**
