### PR TITLE
Provide active tab id to gecko profiler StartProfiler API

### PR DESCRIPTION
**Pull request by canova**
In the `Services.profiler.StartProfiler` API we have an optional parameter to pass the active tab id. It is the identifier for browser's active tab so the profiler can determine which website was inside the browser's active tab during the profiling session.

This is optional because it's not a crucial profiler feature, but it's useful to provide this.
You can see the code similar to this inside Firefox: https://searchfox.org/mozilla-central/rev/d7d2cc647772de15c4c5aa47f74d25d0e379e404/devtools/client/performance-new/popup/background.jsm.js#382-393 and
https://searchfox.org/mozilla-central/rev/d7d2cc647772de15c4c5aa47f74d25d0e379e404/devtools/shared/performance-new/recording-utils.js#16-34

While I was changing this part, I also added some more context in the commments for the API changes that we've done in the past. Hope it's useful!

To test this change locally, you can run it with:
```
node bin/browsertime.js https://sitespeed.io -b firefox --firefox.geckoProfiler --iterations 1
```
and it should produce the profile data inside `<browsetime-results-dir>/pages/sitespeed_io/data/geckoProfile-1.json.gz`.
If you search for `activeTabID` field inside that json, you should see a non-zero value. Previously this field was always zero.

### CODE REVIEW

**Comment by canova** [comment]
Interesting. CI shows that a unit test has failed but I can't reproduce it locally.

**Comment by soulgalore** [comment]
Hi @canova ok cool. I did retry. The thing is that when you run with the profiler turned on using cloud instances (the CI or for example on AWS or Digital Cloud) there's quite often failure like this. I wonder if there could be a limit on memory/CPU or something? However been running it and seen the same on bare metal servers where it just fails on timeouts.

**Comment by canova** [comment]
> Hi @canova ok cool. I did retry. The thing is that when you run with the profiler turned on using cloud instances (the CI or for example on AWS or Digital Cloud) there's quite often failure like this. I wonder if there could be a limit on memory/CPU or something? However been running it and seen the same on bare metal servers where it just fails on timeouts.

Thanks for the retry!

We have some intermittent failures on our CI time to time too I think. It's something we can investigate more. We can maybe try to reduce the profiler buffer size more (current default is ~100MB) for the tests, so it doesn't restrain the CI memory.

But are we running the gecko profiler inside the unit tests at all? I couldn't find any gecko profiler related unit test in the codebase.  There is only one geckoProfiler run in [linux.yml file](https://github.com/sitespeedio/browsertime/blob/31402fc7ba7ada5ff470e9c0302a0a14f1d74a53/.github/workflows/linux.yml#L64-L65). I think that might be unrelated.

**Comment by canova** [comment]
Btw, is there anything I need to do for this PR? I think it should be ready for review.

**Comment by soulgalore** [comment]
Hi @canova sorry I forgot, let me fix it today.

**Pull request merged**
