### PR TITLE
Use chrome-devtools to collect cpu metrics

### PR DESCRIPTION
**Pull request by soulgalore**
There's one big downsize to use devtools-timeline-model. The size:

`─────────────────────────┬──────────────┬────────┐
│ name                    │ children     │ size   │
├─────────────────────────┼──────────────┼────────┤
│ alto-saxophone          │ 365          │ 17.95M │
├─────────────────────────┼──────────────┼────────┤
│ devtools-timeline-model │ 2            │ 17.59M │
├─────────────────────────┼──────────────┼────────┤
│ selenium-webdriver      │ 32           │ 6.91M  │
├─────────────────────────┼──────────────┼────────┤
│ chrome-har              │ 6            │ 5.00M  │
├─────────────────────────┼──────────────┼────────┤
│ soprano-saxophone       │ 2            │ 3.48M  │
├─────────────────────────┼──────────────┼────────┤
│ adbkit                  │ 10           │ 3.01M  │
├─────────────────────────┼──────────────┼────────┤
│ moment                  │ 0            │ 2.20M  │
├─────────────────────────┼──────────────┼────────┤
│ yargs                   │ 63           │ 0.85M  │
├─────────────────────────┼──────────────┼────────┤
│ xvfb                    │ 2            │ 0.64M  │
├─────────────────────────┼──────────────┼────────┤
│ bluebird                │ 0            │ 0.59M  │
├─────────────────────────┼──────────────┼────────┤
│ intel                   │ 13           │ 0.26M  │
├─────────────────────────┼──────────────┼────────┤
│ hasbin                  │ 1            │ 0.25M  │
├─────────────────────────┼──────────────┼────────┤
│ execa                   │ 15           │ 0.13M  │
├─────────────────────────┼──────────────┼────────┤
│ @sitespeed.io/throttle  │ 9            │ 0.13M  │
├─────────────────────────┼──────────────┼────────┤
│ mkdirp                  │ 1            │ 0.07M  │
├─────────────────────────┼──────────────┼────────┤
│ lodash.groupby          │ 0            │ 0.07M  │
├─────────────────────────┼──────────────┼────────┤
│ lodash.remove           │ 0            │ 0.06M  │
├─────────────────────────┼──────────────┼────────┤
│ lodash.merge            │ 0            │ 0.06M  │
├─────────────────────────┼──────────────┼────────┤
│ fast-stats              │ 0            │ 0.04M  │
├─────────────────────────┼──────────────┼────────┤
│ lodash.set              │ 0            │ 0.03M  │
├─────────────────────────┼──────────────┼────────┤
│ lodash.get              │ 0            │ 0.03M  │
├─────────────────────────┼──────────────┼────────┤
│ lodash.isempty          │ 0            │ 0.02M  │
├─────────────────────────┼──────────────┼────────┤
│ lodash.foreach          │ 0            │ 0.02M  │
├─────────────────────────┼──────────────┼────────┤
│ lodash.pick             │ 0            │ 0.02M  │
├─────────────────────────┼──────────────┼────────┤
│ valid-url               │ 0            │ 0.02M  │
├─────────────────────────┼──────────────┼────────┤
│ 25 modules              │ 295 children │ 51.85M │
└─────────────────────────┴──────────────┴────────┘`

### CODE REVIEW

**Comment by soulgalore** [comment]
From a Docker perspective it doesn't matter much. This is the current sizes:

```
sitespeedio/browsertime          2.1.6-wpr-alpha-with-devtools       2.82GB
sitespeedio/browsertime          2.1.6-wpr-alpha                     2.79GB
sitespeedio/browsertime          2.1.6                               1.47GB
```
WebPageReplay and go increases really much, maybe we can make that install better.

**Comment by soulgalore** [comment]
Just to clarify what metrics we collect:
```
"cpu": [
		{
			"activity": {
				"Layout": 1072.7359999418259,
				"RecalculateStyle": 330.770000398159,
				"UpdateLayerTree": 275.65199959278107,
				"ParseHTML": 89.63200008869171,
				"EvaluateScript": 81.62900006771088,
				"AnimationFrameFired": 53.674999952316284,
				"FireIdleCallback": 41.0349999666214,
				"Paint": 38.132000267505646,
				"DOMGC": 34.95700001716614,
				"MinorGC": 14.39300000667572,
				"CompileScript": 10.50299996137619,
				"MajorGC": 5.119000017642975,
				"ParseStylesheet": 4.300999939441681
			},
			"category": {
				"rendering": 1679.157999932766,
				"scripting": 241.31099998950958,
				"loading": 93.93300002813339,
				"painting": 38.132000267505646
			}
		}, ....

"cpu": {
			"category": {
				"rendering": {
					"median": 1464,
					"mean": 1530,
					"mdev": 52.93016458880507,
					"min": 1446,
					"p10": 1446,
					"p90": 1679,
					"p99": 1679,
					"max": 1679
				},
				"scripting": {
					"median": 285,
					"mean": 274,
					"mdev": 11.621817140118418,
					"min": 241,
					"p10": 241,
					"p90": 295,
					"p99": 295,
					"max": 295
				},
				"loading": {
					"median": 81,
					"mean": 83,
					"mdev": 4.131936241596864,
					"min": 74,
					"p10": 74,
					"p90": 94,
					"p99": 94,
					"max": 94
				},
				"painting": {
					"median": 30,
					"mean": 33,
					"mdev": 1.870929303287398,
					"min": 30,
					"p10": 30,
					"p90": 38,
					"p99": 38,
					"max": 38
				}
			},
			"activity": {
				"Layout": {
					"median": 950,
					"mean": 987,
					"mdev": 30.51005639776724,
					"min": 938,
					"p10": 938,
					"p90": 1073,
					"p99": 1073,
					"max": 1073
				},
				"RecalculateStyle": {
					"median": 343,
					"mean": 343,
					"mdev": 4.8687745213719476,
					"min": 331,
					"p10": 331,
					"p90": 355,
					"p99": 355,
					"max": 355
				},
				"UpdateLayerTree": {
					"median": 172,
					"mean": 200,
					"mdev": 26.85777415527836,
					"min": 154,
					"p10": 154,
					"p90": 276,
					"p99": 276,
					"max": 276
				},
				"ParseHTML": {
					"median": 77,
					"mean": 79,
					"mdev": 3.9944507804464,
					"min": 70,
					"p10": 70,
					"p90": 90,
					"p99": 90,
					"max": 90
				},
				"EvaluateScript": {
					"median": 84,
					"mean": 86,
					"mdev": 2.048627419921049,
					"min": 82,
					"p10": 82,
					"p90": 91,
					"p99": 91,
					"max": 91
				},
				"AnimationFrameFired": {
					"median": 87,
					"mean": 76,
					"mdev": 7.854732390475198,
					"min": 54,
					"p10": 54,
					"p90": 87,
					"p99": 87,
					"max": 87
				},
				"FireIdleCallback": {
					"median": 44,
					"mean": 43,
					"mdev": 0.6957375180996178,
					"min": 41,
					"p10": 41,
					"p90": 44,
					"p99": 44,
					"max": 44
				},
				"Paint": {
					"median": 30,
					"mean": 33,
					"mdev": 1.870929303287398,
					"min": 30,
					"p10": 30,
					"p90": 38,
					"p99": 38,
					"max": 38
				},
				"DOMGC": {
					"median": 36,
					"mean": 36,
					"mdev": 0.3390135218510515,
					"min": 35,
					"p10": 35,
					"p90": 37,
					"p99": 37,
					"max": 37
				},
				"MinorGC": {
					"median": 19,
					"mean": 19,
					"mdev": 1.6517375906589684,
					"min": 14,
					"p10": 14,
					"p90": 22,
					"p99": 22,
					"max": 22
				},
				"CompileScript": {
					"median": 11,
					"mean": 11,
					"mdev": 0.3857909752783002,
					"min": 10,
					"p10": 10,
					"p90": 12,
					"p99": 12,
					"max": 12
				},
				"MajorGC": {
					"median": 4,
					"mean": 4,
					"mdev": 0.45182913911156247,
					"min": 3,
					"p10": 3,
					"p90": 5,
					"p99": 5,
					"max": 5
				},
				"ParseStylesheet": {
					"median": 4,
					"mean": 4,
					"mdev": 0.13987909769783913,
					"min": 4,
					"p10": 4,
					"p90": 4,
					"p99": 4,
					"max": 4
				}
			}
```

**Comment by soulgalore** [comment]
@tobli @beenanner I've pushed this branch at work and there are a couple of problems. But first you can check the "Time spent" graphs here: https://grafana.wikimedia.org/dashboard/db/webpagereplay

Right now we only push the categories to Graphite and it looks quite ok.

The problems:
1. Scripting time seems to be too low in the devtools-timeline lib: https://github.com/paulirish/devtools-timeline-model/issues/29
2. I'm not sure of the best way to push the deeper details (right now in the PR I use the EventName group). I've asked for recommendations here: https://github.com/paulirish/devtools-timeline-model/issues/30
3. We had a couple of occasions where the numbers are too low, but I haven't had time to check if the problem is in the devtools-timeline, the trace log or how I pick the metrics. Look at this graph: 
screen shot 2018-01-27 at 21 10 41

All other numbers look ok for that run except the ones from the trace log.

I really wanna merge this branch but wanna know more about the three problems first.

**Comment by soulgalore** [comment]
I compared the devtools.timeline project and https://github.com/WPO-Foundation/trace-parser and it seems the trace-parser gets better metrics:
https://phabricator.wikimedia.org/T185874#3927554

I think we can either use that instead (and get rid off 20 mb dependency) or port parts of it to nodejs.

**Comment by soulgalore** [comment]
Let us do https://github.com/sitespeedio/browsertime/pull/434 instead

**Comment by manojs1978** [comment]
hi peter,
how can i get only cpu metrices ?
can i use only --cpu to get all above metrices

**Comment by manojs1978** [comment]
i need only below values

category": {
				"rendering": 1679.157999932766,
				"scripting": 241.31099998950958,
				"loading": 93.93300002813339,
				"painting": 38.132000267505646
			}

**Comment by soulgalore** [comment]
Hi @manojs1978 checkout https://www.sitespeed.io/documentation/sitespeed.io/cpu/ 

Best
Peter

**Pull request closed without merging**
