### PR TITLE
Add an option for webdriver navigation (instead of window.location writes)

### PR DESCRIPTION
**Pull request by acreskeyMoz**
The option, `webdriverPageload`, is defaulted off.
When enabled, pageload navigation will be started with `webdriver.get({url})`.

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @acreskeyMoz cool,  can you add the option in one of the tests in https://github.com/sitespeedio/browsertime/blob/main/.github/workflows/linux.yml so we automatically test the code path + also give some background on how you will use it, just so I know about the background!

Thanks

**Comment by soulgalore** [comment]
Also you can fix the linting with `npm run lint:fix` (I need to add that to the documentation).

**Comment by acreskeyMoz** [comment]
Thanks @soulgalore, I'm on it :)

**Comment by acreskeyMoz** [comment]
One build error on OSX:
```
Run sudo safaridriver --enable
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
```

**Comment by soulgalore** [comment]
There's some problem with OS X setup, started a day ago or so, lets merge without that.

**Comment by soulgalore** [comment]
Thank you @acreskeyMoz !

**Pull request merged**
