### PR TITLE
First step to support tcpdumps

### PR DESCRIPTION
**Pull request by soulgalore**
This will replace #604 since those fixes wasn't done in that PR.

### CODE REVIEW

**Comment by soulgalore** [comment]
Hey @rmarx could you help me verify that this work as you need? Anything that is missing? You can try by checkout the branch and run:
`bin/browsertime.js --tcpdump https://www.sitespeed.io ` 

I've only tried it in the Docker container so far, I'm still traveling:
```
docker build -t sitespeedio/browsertime .
docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime https://www.sitespeed.io/ -n 1 --tcpdump
```

**Comment by soulgalore** [comment]
I think this should be enough. Let us do a follow up when you Robin or someone else tested :)

**Comment by phongiswindy** [comment]
@soulgalore Thank you for adding the `tcpdump` feature. I just tested it and could capture the pcap file. However, this file seems to be damaged as indicated when reading with both `wireshark` and `tcpdump` cmd.

Wireshark error:
image

`tcpdump -r 1.pcap` error:
tcpdump: pcap_loop: truncated dump file; tried to read 262 captured bytes, only got 140

For your ready reference, I also attach the pcap file here.
[1.pcap.zip](https://github.com/sitespeedio/browsertime/files/4189997/1.pcap.zip)

**Comment by soulgalore** [comment]
@phongiswindy what happens if you add some extra wait time before ending the test? For example `--browsertime.pageCompleteWaitTime 5000`? Do you run anything else on that machine running the test? 

One thing I think we could change is stopping tcpdump after we close the browser, now we stops it early when the test is finished, before we collect metrics.

**Comment by soulgalore** [comment]
hmm yeah closing it after the browser will be hard for scripting/testing multiple URLs. If you can test if it helps to wait longer and that helps, let me know.

**Comment by phongiswindy** [comment]
> @phongiswindy what happens if you add some extra wait time before ending the test? For example `--browsertime.pageCompleteWaitTime 5000`? Do you run anything else on that machine running the test?
> 
> One thing I think we could change is stopping tcpdump after we close the browser, now we stops it early when the test is finished, before we collect metrics.

I don't run anything else on the testing machine, I run browsertime in a container so it should be the solely program running. I tried add `--pageCompleteWaitTime 5000` and got this error.
```
Google Chrome 80.0.3987.87 
Mozilla Firefox 72.0
[2020-02-12 13:49:35] INFO: Running tests using Firefox - 1 iteration(s)
[2020-02-12 13:49:38] INFO: Testing url http://bbc.com iteration 1
[2020-02-12 13:54:43] ERROR: Failed waiting on page to finished loading, timed out after 300000 ms BrowserError: Running page complete check 
return (function(waitTime) {
    try { 
            var end = window.performance.timing.loadEventEnd;
            var start= window.performance.timing.navigationStart;
            return (end > 0) && (performance.now() > end - start + waitTime);
    } 
    catch(e) {
        return true;
    }
})(arguments[arguments.length - 1]);
 took too long
return (function(waitTime) {
    try { 
            var end = window.performance.timing.loadEventEnd;
            var start= window.performance.timing.navigationStart;
            return (end > 0) && (performance.now() > end - start + waitTime);
    } 
    catch(e) {
        return true;
    }
})(arguments[arguments.length - 1]);
 took too long
    at /usr/src/app/lib/core/seleniumRunner.js:39:38
    at new Promise (<anonymous>)
    at timeout (/usr/src/app/lib/core/seleniumRunner.js:38:5)
    at SeleniumRunner.wait (/usr/src/app/lib/core/seleniumRunner.js:168:13)
    at SeleniumRunner.loadAndWait (/usr/src/app/lib/core/seleniumRunner.js:241:20)
    at async Measure.start (/usr/src/app/lib/core/engine/command/measure.js:201:9)
    at async /usr/src/app/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/lib/core/engine/iteration.js:181:9)
    at async Engine.runByScript (/usr/src/app/lib/core/engine/index.js:124:20)
    at async run (/usr/src/app/bin/browsertime.js:48:22)
[2020-02-12 13:54:43] INFO: URL failed to load, trying 5 more time(s): Failed waiting on page to finished loading, timed out after 300000 ms 
```

**Comment by soulgalore** [comment]
I wonder if it could be some internal Docker traffic that is picked up? Running without Docker seems to work.

**Comment by soulgalore** [comment]
@phongiswindy there's a hidden feature where you can pass on parameters to tcpdump with `--browsertime.tcpDumpParams` then you should be able to skip local traffic with something like:
`--tcpDumpParams not --tcpDumpParams host --tcpDumpParams 127.0.0.1` but haven't tried it yet :)

**Comment by phongiswindy** [comment]
> --tcpDumpParams not --tcpDumpParams host

@soulgalore, Thank you so much for pointing me to hidden feature. I was able to capture the full pcap. So what happened was `tcpdump` doesn't flush captured packets immediately while the process was killed before it could flush. So to remedy this problem, I passed `--tcpDumpParams='-U'` to flush packets to file as soon as they are captured, thus solving the problem.

**Comment by soulgalore** [comment]
Ah great, let me see if I can add that in the next release.

**Pull request merged**
