### PR TITLE
New default check avoiding using date

### PR DESCRIPTION
**Pull request by soulgalore**

### CODE REVIEW

**Comment by soulgalore** [comment]
Ah sorry I missed the context: When we do the testing in WebPageReplay there's a hack that make sure that the Javascript Date now never change (so that each iteration will be the same). That hack makes our current pageComplete check unusable (it never times out). 

If we gonna merge the two Dockerfiles into one (we have one default now and one that includes WebPageReplay) it would be neat if we can use the same script that works across the board. However right now we cannot merge it because WPR adds something like 1gb to the container.

Let me update the script.

**Comment by marty90** [comment]
BTW: I'm using the standard `browsertime` container and `WPR`. I had the issued mentioned above (the `Date` hack made `browsertime` hang). Using `--pageCompleteCheckInactivity` solved the issue for me ;)

**Comment by marty90** [comment]
I'm actually using browsertime without any customization for WebPageReplay (for some other reasons). The default browsertime check makes browsertime hang even with the last version.

**Comment by soulgalore** [comment]
Cool, yep then I see, thanks!

**Pull request closed without merging**
