### PR TITLE
Revert the orange frame workaround we did for Firefox

### PR DESCRIPTION
**Pull request by sefeng211**
In https://bugzilla.mozilla.org/show_bug.cgi?id=1606365,
we did a workaround to fix a Firefox issue, and
this issue is no longer persist, so we can remove this changes.

### CODE REVIEW

**Comment by sefeng211** [comment]
Hmm, there's a test failure on Firefox, @soulgalore is this legit? 
```
Error: 8-03 15:30:14][ERROR] Got an error from HAR Export Trigger {"error":"The HAR export trigger returned an empty HAR{\"version\":\"1.2\",\"creator\":{\"name\":\"Firefox\",\"version\":\"103.0.1\"},\"browser\":{\"name\":\"Firefox\",\"version\":\"103.0.1\"},\"pages\":[],\"entries\":[]}"}
  ✖ engineTest › Load one URL with none page load strategy Rejected promise returned by test
Error: 8-03 15:30:14][ERROR] TypeError: Cannot read properties of undefined (reading 'log')
```

**Comment by soulgalore** [comment]
Yep it is legit in the way that something is wrong but it do not depend on your change. That error started to happen a couple of Firefox releases again but mostly on GitHub actions and not everytime.

**Comment by soulgalore** [comment]
@sefeng211 I'll be back home on Friday and can merge then but feel free to self merge before that if you want. Thank you for creating the revert :)

**Comment by soulgalore** [comment]
thank you @sefeng211 !

**Pull request merged**
