### PR TITLE
Make sure ffmpeg finished  before  moving on.

### PR DESCRIPTION
**Pull request by soulgalore**
The current implementation was sloppy by me, we don't actually wait on ffmpeg to finish before we move on (as seen by @gmierz ).

### CODE REVIEW

**Comment by soulgalore** [comment]
I think this would fix the strange things you've been seeing @gmierz !

**Comment by gmierz** [comment]
I still have the issue if I move the code to save the original before the orange frame removal. Here's the stack trace I got:
```
21:35:39     INFO -  raptor-browsertime Info: Get visual metrics from the video
21:35:40    ERROR -  raptor-browsertime Error: Browsertime failed to run
21:35:40     INFO -  raptor-browsertime Info: ffmpeg version 4.0.3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
21:35:40     INFO -  raptor-browsertime Info:   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
21:35:40     INFO -  raptor-browsertime Info:   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
21:35:40     INFO -  raptor-browsertime Info:   libavutil      56. 14.100 / 56. 14.100
21:35:40     INFO -  raptor-browsertime Info:   libavcodec     58. 18.100 / 58. 18.100
21:35:40     INFO -  raptor-browsertime Info:   libavformat    58. 12.100 / 58. 12.100
21:35:40     INFO -  raptor-browsertime Info:   libavdevice    58.  3.100 / 58.  3.100
21:35:40     INFO -  raptor-browsertime Info:   libavfilter     7. 16.100 /  7. 16.100
21:35:40     INFO -  raptor-browsertime Info:   libswscale      5.  1.100 /  5.  1.100
21:35:40     INFO -  raptor-browsertime Info:   libswresample   3.  1.100 /  3.  1.100
21:35:40     INFO -  raptor-browsertime Info:   libpostproc    55.  1.100 / 55.  1.100
21:35:40     INFO -  raptor-browsertime Info: /home/sparky/mozilla-source/mozilla-central/testing/mozharness/build/blobber_upload_dir/browsertime-results/process-switch/pages/mozilla_pettay_fi/moztests/blue.html/data/video/1.mp4: No such file or directory
21:35:40     INFO -  raptor-browsertime Info: ffmpeg version 4.0.3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
21:35:40     INFO -  raptor-browsertime Info:   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
21:35:40     INFO -  raptor-browsertime Info:   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
21:35:40     INFO -  raptor-browsertime Info:   libavutil      56. 14.100 / 56. 14.100
21:35:40     INFO -  raptor-browsertime Info:   libavcodec     58. 18.100 / 58. 18.100
21:35:40     INFO -  raptor-browsertime Info:   libavformat    58. 12.100 / 58. 12.100
21:35:40     INFO -  raptor-browsertime Info:   libavdevice    58.  3.100 / 58.  3.100
21:35:40     INFO -  raptor-browsertime Info:   libavfilter     7. 16.100 /  7. 16.100
21:35:40     INFO -  raptor-browsertime Info:   libswscale      5.  1.100 /  5.  1.100
21:35:40     INFO -  raptor-browsertime Info:   libswresample   3.  1.100 /  3.  1.100
21:35:40     INFO -  raptor-browsertime Info:   libpostproc    55.  1.100 / 55.  1.100
21:35:40     INFO -  raptor-browsertime Info: /home/sparky/mozilla-source/mozilla-central/testing/mozharness/build/blobber_upload_dir/browsertime-results/process-switch/pages/mozilla_pettay_fi/moztests/blue.html/data/video/1.mp4: No such file or directory
21:35:40     INFO -  raptor-browsertime Info:     at makeError (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/execa/lib/error.js:60:11)
21:35:40     INFO -  raptor-browsertime Info:     at Function.module.exports.sync (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/execa/index.js:194:17)
21:35:40     INFO -  raptor-browsertime Info:     at module.exports (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/lib/video/postprocessing/finetune/removeOrange.js:23:16)
21:35:40     INFO -  raptor-browsertime Info:     at module.exports (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/lib/video/postprocessing/finetune/index.js:34:11)
21:35:40     INFO -  raptor-browsertime Info:     at async Video.postProcessing (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/lib/video/video.js:107:7)
21:35:40     INFO -  raptor-browsertime Info:     at async Iteration.run (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/lib/core/engine/iteration.js:261:34)
21:35:40     INFO -  raptor-browsertime Info:     at async Engine.runByScript (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/lib/core/engine/index.js:266:20)
21:35:40     INFO -  raptor-browsertime Info:     at async run (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/bin/browsertime.js:71:22)
21:35:40    ERROR -  raptor-browsertime Error: Browsertime failed to run
21:35:40     INFO -  raptor-browsertime Info:     at Iteration.run (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/lib/core/engine/iteration.js:285:31)
21:35:40     INFO -  raptor-browsertime Info:     at async Engine.runByScript (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/lib/core/engine/index.js:266:20)
21:35:40     INFO -  raptor-browsertime Info:     at async run (/home/sparky/mozilla-source/mozilla-central/tools/browsertime/node_modules/browsertime/bin/browsertime.js:71:22)
21:35:40    ERROR -  raptor-browsertime Critical: TypeError: Cannot read properties of undefined (reading 'push')
```

**Comment by gmierz** [comment]
Ah whoops! I just needed to change this to a copy instead of rename:
```
  if (get(options, 'videoParams.keepOriginalVideo', false)) {
    const originalFile = path.join(videoDir, index + '-original.mp4');
    await copyFile(videoPath, originalFile);
  }
```

With that change to copy everything works and I don't get the error. I tested with and without this `.sync`, and there was no difference. Maybe it could still help other things though?

**Comment by soulgalore** [comment]
I think the video code could do some cleanup so its more easy to follow, I'll create a task for that and then push the other changes later today so you can move on.

**Pull request closed without merging**
