### PR TITLE
Add commands for scrolling, mouse events, navigation, and new tabs/windows

### PR DESCRIPTION
**Pull request by dpalmeiro**
This patch adds several new commands to help measure page interactions:
- scrolling by Pixels, Lines or Pages
- forward, back or refresh navigations
- create new tabs or windows and switch to them
- new mouse events such as context click, single click, double click, click and hold, release, and movement

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @dpalmeiro great! When its ready can also please make a PR to update the documentation for commands at https://github.com/sitespeedio/sitespeed.io/blob/main/docs/documentation/sitespeed.io/scripting/index.md ? That would be super helpful!

**Comment by dpalmeiro** [comment]
> 
> 
> Hi @dpalmeiro great! When its ready can also please make a PR to update the documentation for commands at https://github.com/sitespeedio/sitespeed.io/blob/main/docs/documentation/sitespeed.io/scripting/index.md ? That would be super helpful!

Yes, I definitely will. Thanks.

**Comment by soulgalore** [comment]
Great! If you run `npm run lint:fix` it will fix the linting issues.

**Comment by soulgalore** [comment]
Great thanks you @dpalmeiro !

**Review by chrystianrgs — APPROVED** [review]

**Pull request merged**
