### PR TITLE
fix browser info bar for visual metrics

### PR DESCRIPTION
**Pull request by pan-alexey**

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @pan-alexey thanks for the PR. I think the best way is to fix this in Visual Metrics, the magic happens here: https://github.com/sitespeedio/browsertime/blob/main/browsertime/visualmetrics.py#L595-L603.

**Comment by soulgalore** [comment]
Hi @pan-alexey just want to verify how you get 24 to be the right value?

**Comment by pan-alexey** [comment]
> Hi @pan-alexey just want to verify how you get 24 to be the right value?

I get size in video (create snapshot videos in vlc) and put this in Photoshop

https://files.slack.com/files-pri/T03DHTPR2-F017ZPT6PJP/image.png

**Comment by soulgalore** [comment]
Thank you @pan-alexey !

**Comment by soulgalore** [comment]
FYI @pan-alexey pushed this in 9.2.1. Thank you again!

**Pull request merged**
