### PR TITLE
fix #1577 issue with cookies containing equals sign in value

### LINKED ISSUE #1577: Cookies containing "=" character in values are truncated
Cookies containing "=" in values are truncated because of this line : 

https://github.com/sitespeedio/browsertime/blob/main/lib/chrome/chromeDevtoolsProtocol.js#L134

### PR DESCRIPTION
**Pull request by sebguilbaud**
Cookies with "=" in values are not correctly handled by split(), the following patch fixes #1577

### CODE REVIEW

**Comment by sebguilbaud** [comment]
Hi @soulgalore, is there something blocking this PR ?

**Comment by sebguilbaud** [comment]
thanks :+1:

**Comment by sebguilbaud** [comment]
I'm going to update this PR for failing eslint tests @soulgalore

**Comment by sebguilbaud** [comment]
PR updated according to eslint warnings @soulgalore

**Comment by soulgalore** [comment]
Thank you @sebguilbaud

**Pull request merged**
