### PR TITLE
Configure http and https proxies separately.

### PR DESCRIPTION
**Pull request by tobli**
E.g. --proxy.http=example.com:1234 and  --proxy.https=example.net:2345.

### CODE REVIEW

**Comment by softwareklinic** [comment]
Can site speed be passed the --proxy.http parameter??

**Comment by soulgalore** [comment]
@softwareklinic yes just prepend with browsertime: --browsertime.proxy.http

**Comment by softwareklinic** [comment]
do i need to give prefix http:// and https://

since our proxy is same for both http and https e.g. http://xxxx.xxxx.com:80

**Comment by soulgalore** [comment]
Hey @softwareklinic,
you should leave out the protocol and just add the domain and port.

I think you could just run the https if your proxy can handle the https correctly but I'm not sure. It would be great if you could add a comment here what worked for you so everyone knows in the future.

Thanks!
Peter

**Comment by softwareklinic** [comment]
Here is what I tried using below OS, SITESPEED, Browsertime config
AWS RHEL 7 - docker
[2016-11-23 04:56:18] Versions OS: linux 3.10.0-327.3.1.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.0.7 browsertime: 1.0.0-beta.11 coach: 0.29.0


**ATTEMPT 1**  - FAILED WITH PROXY ARGS

docker run --privileged -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io https://www.verizonwireless.com -n 1 --browsertime.proxy.http=proxy.xxxx.xxxxxxxxx.com:80 --browsertime.proxy.https=proxy.xxxx.xxxxxxxxx.com:80

[2016-11-23 04:50:57] Browser failed to start in time, trying one more time.
[2016-11-23 04:51:57] https://www.verizonwireless.com generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: crashed

**ATTEMPT 2** - FAILED - WITHOUT PROXY ARGS

docker run --privileged -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io https://www.verizonwireless.com -n 1

[2016-11-23 04:53:18] Browser failed to start in time, trying one more time.
[2016-11-23 04:54:19] https://www.verizonwireless.com generated the following error in Browsertime BrowserError: Failed to start browser in 60 seconds.

**ATTEMPT 3** - WORKED - with PROXY and FIREFOX

docker run --privileged -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io https://www.verizonwireless.com -n 1 --browsertime.proxy.http=proxy.xxxx.xxxxxxx.com:80 --browsertime.proxy.https=proxy.xxxx.xxxxxxxx.com:80 -b firefox

**ATTEMPT 4** - FAILED - with PROXY and CHROME

docker run --privileged -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io https://www.verizonwireless.com -n 1 --browsertime.proxy.http=proxy.xxxx.xxxxx.com:80 --browsertime.proxy.https=proxy.xxxxx.xxxxx.com:80 -b chrome

[2016-11-23 04:57:18] Browser failed to start in time, trying one more time.
[2016-11-23 04:58:18] https://www.verizonwireless.com generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: crashed

**Comment by softwareklinic** [comment]
Looks like some issue with CHROME - keeps crashing....

**Comment by beenanner** [comment]
Does it  work with an Ubuntu machine @softwareklinic? Seeing a few issues around the web on RHEL 7 and chrome, so wondering if it's that combo.

**Comment by softwareklinic** [comment]
We cannot try/use ubuntu - since its not supported by our ops group. Only RHEL.

**Comment by softwareklinic** [comment]
But the sitespeed docker image is running ubuntu right??? --- how does the host OS make any difference... just curious?

**Comment by tobli** [comment]
Try adding --shm-size=1g to docker run when running Chrome.

**Comment by beenanner** [comment]
@tobli beat me to it. I always forget about that blasted option :-p

**Comment by softwareklinic** [comment]
Trying it right away -

**Comment by softwareklinic** [comment]
is that the exact option --shm-size=1g

im getting flag provided but not defined: --shm-size

**Comment by softwareklinic** [comment]
docker run --privileged --shm-size=1g -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io

**Comment by softwareklinic** [comment]
Oh === looks like its a Docker build option... and not for docker run... so i will wait for next build on hub.docker.com --- i can definitely try to build on my local... but i was trying this out on my AWS instance

**Comment by soulgalore** [comment]
Hey @softwareklinic it is for run but I think it was added in a later version of docker so I think you need to upgrade:
<pre>
docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/
</pre>

Best
Peter

**Comment by softwareklinic** [comment]
upgrading....

**Comment by softwareklinic** [comment]
Still the same 

docker run --privileged --shm-size=1g -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io https://www.verizonwireless.com -n 1 with proxy settings

[2016-11-23 07:36:25] Testing url https://www.verizonwireless.com run 1
[2016-11-23 07:37:25] https://www.verizonwireless.com generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)

**Comment by softwareklinic** [comment]
Changed it to 2g --- and now it says browser failed to start on time... trying one more time

Changed it to 3g --- and same effect as 2g...

But 2g and 3g --- chrome didnt crash -- just that it complained about browser failed to start on time....

**Comment by beenanner** [comment]
@softwareklinic possibly kernel related which is why I suggested another OS? Yes the containers run on Ubuntu, but they still share the host kernel. Does your ops have the ability to possible try upgrading the kernel to something new than 3.10. I tried it on my AWS account and it failed with the default 3.10.x, but after upgrading the kernel it seems to work.

```
[ec2-user@ip-172-31-61-126 ~]$ docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/
Unable to find image 'sitespeedio/sitespeed.io:latest' locally
latest: Pulling from sitespeedio/sitespeed.io
6bbedd9b76a4: Pull complete
fc19d60a83f1: Pull complete
de413bb911fd: Pull complete
2879a7ad3144: Pull complete
668604fde02e: Pull complete
4bc52c2a6979: Pull complete
f35c37874afa: Pull complete
a80ffcc161e6: Pull complete
5983298ea57d: Pull complete
f9984da1147d: Pull complete
fcc9456c65f3: Pull complete
af8c9748b2f1: Pull complete
767ff2d389a1: Pull complete
d61d1e7f5cac: Pull complete
2302b4f0a43c: Pull complete
c3aa460fde0c: Pull complete
a974b66104b1: Pull complete
9c04650dded8: Pull complete
Digest: sha256:9a4de44562d3b35b9901f06a4397a7f468c714ce0581a00687923e8565c87d97
Status: Downloaded newer image for sitespeedio/sitespeed.io:latest
Google Chrome 54.0.2840.71
Mozilla Firefox 49.0.2
[2016-11-23 19:30:00] Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.0.7 browsertime: 1.0.0-beta.11 coach: 0.29.0
[2016-11-23 19:30:00] Starting chrome for analysing https://www.sitespeed.io/ 3 time(s)
[2016-11-23 19:30:00] Testing url https://www.sitespeed.io/ run 1
[2016-11-23 19:31:00] Browser failed to start in time, trying one more time.
[2016-11-23 19:32:01] https://www.sitespeed.io/ generated the following error in Browsertime BrowserError: Failed to start browser in 60 seconds.
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:74:15)
From previous event:
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:73:13)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:202:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:277:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:276:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:275:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:26)
    at /usr/src/app/node_modules/xvfb/index.js:55:28
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:8)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:129:27)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
    at SeleniumRunner.startBrowser (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:37:10)
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:42:25)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:202:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:277:25)
[2016-11-23 19:32:01] Render HTML for 1 page(s)
[2016-11-23 19:32:01] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2016-11-23-19-30-00
[2016-11-23 19:32:01] Finished analysing https://www.sitespeed.io/


[ec2-user@ip-172-31-61-126 ~]$ docker run --privileged --shm-size=1g -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io https://www.verizonwireless.com -n 1
Google Chrome 54.0.2840.71
Mozilla Firefox 49.0.2
[2016-11-23 19:32:21] Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.0.7 browsertime: 1.0.0-beta.11 coach: 0.29.0
[2016-11-23 19:32:21] Starting chrome for analysing https://www.verizonwireless.com 1 time(s)
[2016-11-23 19:32:21] Testing url https://www.verizonwireless.com run 1
[2016-11-23 19:33:21] Browser failed to start in time, trying one more time.
[2016-11-23 19:34:21] https://www.verizonwireless.com generated the following error in Browsertime BrowserError: Failed to start browser in 60 seconds.
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:74:15)
From previous event:
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:73:13)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:202:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:277:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:276:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:275:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:26)
    at /usr/src/app/node_modules/xvfb/index.js:55:28
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:8)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:129:27)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
    at SeleniumRunner.startBrowser (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:37:10)
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:42:25)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:202:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:277:25)
[2016-11-23 19:34:21] Render HTML for 1 page(s)
[2016-11-23 19:34:22] HTML stored in /sitespeed.io/sitespeed-result/www.verizonwireless.com/2016-11-23-19-32-21
[2016-11-23 19:34:22] Finished analysing https://www.verizonwireless.com
```

vs

```
[ec2-user@ip-172-31-61-126 ~]$ docker run --privileged --shm-size=1g -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io https://www.verizonwireless.com -n 1
Google Chrome 54.0.2840.71
Mozilla Firefox 49.0.2
[2016-11-23 19:48:28] Versions OS: linux 4.8.10-1.el7.elrepo.x86_64 nodejs: v6.9.1 sitespeed.io: 4.0.7 browsertime: 1.0.0-beta.11 coach: 0.29.0
[2016-11-23 19:48:28] Starting chrome for analysing https://www.verizonwireless.com 1 time(s)
[2016-11-23 19:48:28] Testing url https://www.verizonwireless.com run 1
[2016-11-23 19:49:35] 155 requests, 2584.22 kb, firstPaint: 1.22s, DOMContentLoaded: 1.59s, Load: 3.34s, rumSpeedIndex: 1269
[2016-11-23 19:49:35] Render HTML for 1 page(s)
[2016-11-23 19:49:37] HTML stored in /sitespeed.io/sitespeed-result/www.verizonwireless.com/2016-11-23-19-48-28
[2016-11-23 19:49:37] Finished analysing https://www.verizonwireless.com

[ec2-user@ip-172-31-61-126 ~]$ docker run --privileged --shm-size=1g -v /app/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io https://www.verizonwireless.com -n 1
Google Chrome 54.0.2840.71
Mozilla Firefox 49.0.2
[2016-11-23 19:55:01] Versions OS: linux 4.8.10-1.el7.elrepo.x86_64 nodejs: v6.9.1 sitespeed.io: 4.0.7 browsertime: 1.0.0-beta.11 coach: 0.29.0
[2016-11-23 19:55:01] Starting chrome for analysing https://www.verizonwireless.com 1 time(s)
[2016-11-23 19:55:01] Testing url https://www.verizonwireless.com run 1
[2016-11-23 19:55:07] 156 requests, 2582.56 kb, firstPaint: 1.21s, DOMContentLoaded: 1.56s, Load: 2.15s, rumSpeedIndex: 1241
[2016-11-23 19:55:07] Render HTML for 1 page(s)
[2016-11-23 19:55:09] HTML stored in /sitespeed.io/sitespeed-result/www.verizonwireless.com/2016-11-23-19-55-01
[2016-11-23 19:55:09] Finished analysing https://www.verizonwireless.com
```

**Comment by softwareklinic** [comment]
I will give it a try. Thank you for the insights… really appreciate.

**Comment by beenanner** [comment]
Also from the 3.10.x kernel runs it produced core dumps in the output directory for me. You might have some on your instance to checkout for more insight.

[ec2-user@ip-172-31-61-126 ~]$ ls -la /app/sitespeed.io/core.*
-rw-------. 1 root root 19738624 Nov 23 14:32 /app/sitespeed.io/core.36
-rw-------. 1 root root 19738624 Nov 23 14:33 /app/sitespeed.io/core.53

**Comment by softwareklinic** [comment]
Yes I saw those and then deleted… thinking some junk – will generate again

**Pull request merged**
